### ISSUE TITLE
Create issues

### ISSUE THREAD

**Issue by bmthang94** [VictorBui2702/Github-Issue-Page#5]
The user should be able to create a new issue via a modal for the repository, by clicking on a "new issue" button. Clicking on this button will pop open a modal that asks for the requisite fields.
If there is an error creating the issue (for example, the user not supplying all required parameters), there should be a nice error message to the user.

**Comment by AHADATAMT** [comment]
eeee

**Comment by AHADATAMT** [comment]
eeee

**Comment by AHADATAMT** [comment]
e

**Comment by bmthang94** [comment]
Hey

**Comment by bmthang94** [comment]
Oh!
